baseURL = '/'
languageCode = 'en-us'
title = 'Boop'
theme = 'the-roots-home'
author = "Boop"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
  
theme="the-roots-home"

#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true
