baseURL = '/'
languageCode = 'en-us'
title = 'Boop'
theme = 'the-roots-home'
author = "Boop"

DefaultContentLanguage = "en"
enableInlineShortcodes = true
  


#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true
#test
# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true
